//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogsShopTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_FoodPet
    {
        public int Id { get; set; }
        public Nullable<int> DogId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> FoodPetId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual FoodPet FoodPet { get; set; }
        public virtual Order Order { get; set; }
    }
}
